/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. It is included so `tsc` works before the first Vite run.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";

const IndexRoute = IndexRouteImport.update({ id: "/", path: "/", getParentRoute: () => rootRouteImport } as any);
const AboutRoute = AboutRouteImport.update({ id: "/about", path: "/about", getParentRoute: () => rootRouteImport } as any);

export interface FileRoutesByFullPath { "/": typeof IndexRoute; "/about": typeof AboutRoute }
export interface FileRoutesByTo { "/": typeof IndexRoute; "/about": typeof AboutRoute }
export interface FileRoutesById { __root__: typeof rootRouteImport; "/": typeof IndexRoute; "/about": typeof AboutRoute }
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about";
  id: "__root__" | "/" | "/about";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren { IndexRoute: typeof IndexRoute; AboutRoute: typeof AboutRoute }

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { id: "/"; path: "/"; fullPath: "/"; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport };
    "/about": { id: "/about"; path: "/about"; fullPath: "/about"; preLoaderRoute: typeof AboutRouteImport; parentRoute: typeof rootRouteImport };
  }
}

export const routeTree = rootRouteImport
  ._addFileChildren({ IndexRoute, AboutRoute } satisfies RootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
